In [1]:
import pandas as pd

outbound_orders1 = pd.read_csv("OutboundOrders_20210907_aThingz.csv")

C:\Users\amali\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
# imports up here can be used to
import pandas as pd
import datetime

# The entry point function MUST have two input arguments.
# If the input port is not connected, the corresponding
# dataframe argument will be None.
#   Param<dataframe1>: a pandas.DataFrame
#   Param<dataframe2>: a pandas.DataFrame
def azureml_main(dataframe1 = None, dataframe2 = None):

    # Execution logic goes here
    #print(f'Input pandas.DataFrame #1: {dataframe1}')

        

    outbound_orders = dataframe1

    outbound_orders['ORIGIN_FACILITY_ID'] = [str(i) for i in outbound_orders1['ORIGIN_FACILITY_ID']]

    #outbound_orders = outbound_orders.loc[outbound_orders['ORIGIN_FACILITY_ID'] == 'ATL'] 

    
    outbound_orders['ORDER_CREATE_DATE'] = [ datetime.datetime.strptime(i,'%Y-%m-%d %H:%M:%S').strftime('%Y-%m-%d') for i in outbound_orders['ORDER_CREATE_DATE']]
    
    outbound_orders = outbound_orders.groupby(['ITEM_NUMBER', 'ORDER_CREATE_DATE','ORIGIN_FACILITY_ID']).sum()['ORDER_QTY']

    outbound_orders = outbound_orders.to_frame(name = 'ORDER_QTY').reset_index()
    
    
    
    

    
    
    outbound_orders = outbound_orders.fillna(0)

    outbound_orders = pd.melt(outbound_orders,id_vars=['ITEM_NUMBER','ORDER_CREATE_DATE','ORIGIN_FACILITY_ID'],value_vars=['ORDER_QTY'])
    #print(outbound_orders)

    
    



    # If a zip file is connected to the third input port,
    # it is unzipped under "./Script Bundle". This directory is added
    # to sys.path. Therefore, if your zip file contains a Python file
    # mymodule.py you can import it using:
    # import mymodule

    # Return value must be of a sequence of pandas.DataFrame
    # E.g.
    #   -  Single return value: return dataframe1,
    #   -  Two return values: return dataframe1, dataframe2
    dataframe1 = outbound_orders
    

    return dataframe1

In [5]:
azureml_main(outbound_orders1)

         ITEM_NUMBER ORDER_CREATE_DATE ORIGIN_FACILITY_ID   variable  value
0          00TGCKM00        2021-08-16                BAL  ORDER_QTY    1.0
1         04EGSNLPDG        2021-07-13                LAX  ORDER_QTY    1.0
2         04EGSNLPDG        2021-07-30                JAX  ORDER_QTY    5.0
3         04EGSNLPDG        2021-08-17                LAX  ORDER_QTY    1.0
4         04EGSNLPDG        2021-08-20                LAX  ORDER_QTY    1.0
...              ...               ...                ...        ...    ...
1368140  ZWSA24CRDWA        2021-08-16                ATL  ORDER_QTY    1.0
1368141  ZWSA24PRDWB        2021-02-08                ATL  ORDER_QTY    1.0
1368142  ZWSA24PRDWB        2021-02-18                nan  ORDER_QTY   30.0
1368143  ZWSA24PRDWB        2021-03-11                nan  ORDER_QTY   15.0
1368144  ZWSA24PRDWB        2021-05-04                ATL  ORDER_QTY    2.0

[1368145 rows x 5 columns]